 rasp:
  connection:
   adress: kax-gate.noip.me
   type: ssh
   sshport: 443
   remoteport: 5432
   user: nsn
   passwd: nsnshepherd
  databases:
   pgBase_test:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
   pgBasex:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd

 rasp2:
  connection:
   adress: kax-gate.noip.me
   type: ssh
   sshport: 22
   remoteport: 443
   user: nsn
   passwd: nsnshepherd
  databases:
   pgBase_test:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
   pgBasex:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd